### PR TITLE
fix: gazelle failing on Windows with "panic: runtime error: invalid memory address or nil pointer dereference"

### LINKED ISSUE #1871: Gazelle fails on Windows with "panic: runtime error: invalid memory address or nil pointer dereference"
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 
rules_python_gazelle_plugin

### Is this a regression?

No

### Description

`bazel run gazelle` fails on Windows with the below error. As per [Python Gazelle plugin](https://github.com/bazelbuild/rules_python/blob/main/gazelle/README.md):
> Gazelle will walk up the filesystem from a Python file to find this metadata, looking for a file called gazelle_python.yaml in an ancestor folder of the Python code.

and because pythonconfig.go#ParentForPackage delegates to filepath.Dir(pkg) to replace the separator character "\\" with "/", hence for a 2-levels deep path, e.g. rootDir\nestedDir1\nestedDir2, a parent is searched with "/" (rootDir/nestedDir1) but Configs contains a key with "\\" (rootDir\nestedDir1).

## 🔬 Minimal Reproduction

Run rules_python_gazelle_plugin on Windows in a project with at least 2-levels deep directory structure.

## 🔥 Exception or Error
<pre><code>INFO: Running command line: bazel-bin/external/bp_bazel/tools/gazelle/gazelle.exe
INFO: Build Event Protocol files produced successfully.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x7c3122]

goroutine 1 [running]:
github.com/bazelbuild/rules_python/gazelle/pythonconfig.(*Config).NewChild(...)
	external/rules_python_gazelle_plugin/pythonconfig/pythonconfig.go:173
github.com/bazelbuild/rules_python/gazelle/python.(*Configurer).Configure(0xc00036a801?, 0xc0001a4900, {0xc000591a40, 0x18}, 0x0)
	external/rules_python_gazelle_plugin/python/configure.go:92 +0x222
github.com/bazelbuild/bazel-gazelle/walk.configure({0xc00022dcc0, 0xa, 0x18?}, 0xc000149080?, 0xc0001a4840?, {0xc000591a40, 0x18}, 0x0)
	external/bazel_gazelle/walk/walk.go:289 +0x383
github.com/bazelbuild/bazel-gazelle/walk.Walk.func1(0xc0001a4840, {0xc000149080, 0x44}, {0xc000591a40, 0x18}, 0x1)
	external/bazel_gazelle/walk/walk.go:145 +0x2d6
github.com/bazelbuild/bazel-gazelle/walk.Walk.func1(0xc0001a4780, {0xc000525680, 0x3c}, {0xc0001203b0, 0x10}, 0x1)
	external/bazel_gazelle/walk/walk.go:169 +0x8b7
github.com/bazelbuild/bazel-gazelle/walk.Walk.func1(0xc0001a4300, {0xc0003f2b40, 0x34}, {0xc000120300, 0x8}, 0x1)
	external/bazel_gazelle/walk/walk.go:169 +0x8b7
github.com/bazelbuild/bazel-gazelle/walk.Walk.func1(0xc0001a4300, {0xc0001428d0, 0x2b}, {0x0, 0x0}, 0x0)
	external/bazel_gazelle/walk/walk.go:169 +0x8b7
github.com/bazelbuild/bazel-gazelle/walk.Walk(0xc0001a4300, {0xc00022dcc0?, 0xa, 0xa}, {0xc000111a40, 0x1, 0x1}, 0x0, 0xc0001d5648)
	external/bazel_gazelle/walk/walk.go:179 +0x231
main.runFixUpdate({0xc000142690, 0x2b}, 0xc000120080?, {0xc00011a390, 0x0, 0x0})
	external/bazel_gazelle/cmd/gazelle/fix-update.go:325 +0xdc5
main.run({0xc000142690?, 0x2b?}, {0xc00011a390?, 0x1?, 0x1?})
	external/bazel_gazelle/cmd/gazelle/gazelle.go:95 +0x1dd
main.main()
	external/bazel_gazelle/cmd/gazelle/gazelle.go:72 +0xf5</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Windows 11
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.18.0
Build label: 7.1.1
Build target: @@//src/main/java/com/google/devtools/build/lib/bazel:BazelServer
Build time: Thu Mar 21 18:11:32 2024 (1711044692)
Build timestamp: 1711044692
Build timestamp as int: 1711044692

  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.31.0
  </code>
</pre>

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by bartoszpop**
This pull request fixes `bazel run gazelle` failing on Windows with "panic: runtime error: invalid memory address or nil pointer dereference" if there is a path with at least 2-levels deep directory. 

Fixes #1871

### CODE REVIEW

File: gazelle/pythonconfig/pythonconfig.go [hunk 1]
```diff
@@ -126,7 +126,7 @@ type Configs map[string]*Config
 
 // ParentForPackage returns the parent Config for the given Bazel package.
 func (c *Configs) ParentForPackage(pkg string) *Config {
-	dir := filepath.Dir(pkg)
+	dir := path.Dir(pkg)
```
Comment (aignas) [inline gazelle/pythonconfig/pythonconfig.go:129]: Looking at the code, I am not sure it is working the way you think. `path.Dir` will just split at `/` if I understand things correctly and `filepath.Path` is much more sophisticated and I am surprised that this is not working correctly.

I don't have a Windows machine, but the code change looks suspicious.

Comment (bartoszpop) [reply gazelle/pythonconfig/pythonconfig.go:129]: @aignas the same issue I have fixed [here](https://github.com/bazel-contrib/rules_jvm/pull/261). My initial approach was to use `cfgs[filepath.FromSlash(rel)]` but a more targeted fix was prosed in [this](https://github.com/bazel-contrib/rules_jvm/pull/261#issuecomment-2091026233) comment.

Basically, it fails because `pythonconfig.go#ParentForPackage` delegates to filepath.Dir(pkg) to replace the separator character "\" with "/", hence for a 2-levels deep path, e.g. rootDir\nestedDir1\nestedDir2, a parent is searched with "/" (rootDir/nestedDir1) but Configs contains a key with "\" (rootDir\nestedDir1).

Comment (aignas) [reply gazelle/pythonconfig/pythonconfig.go:129]: Ah, I see, thanks for the context, it was much needed here. Could you please rebase and add Changelog notes to the Changelog.md please?

**Comment by aignas** [comment]
The PR looks good to me and I would love to merge it since we have cut a `0.32.2` release. Could you please rebase and update the CHANGELOG.md please?

**Comment by bartoszpop** [comment]
> The PR looks good to me and I would love to merge it since we have cut a `0.32.2` release. Could you please rebase and update the CHANGELOG.md please?

@aignas sorry for the delay, I'll do it by the end of this week.

**Review by aignas — APPROVED** [review]
