### PR TITLE
docs: show PR warning banner and fix links doc source pages

### LINKED ISSUE #1516: docs on readthedocs aren't showing some standard features
Our docs on readthedocs seem to be missing a couple of things that usually show up:

* PR builds don't show a warning banner (https://docs.readthedocs.io/en/stable/pull-requests.html)
* The mentions of github aren't shown on pages and in the flyout menu. Compare with https://rules-testing.readthedocs.io/en/latest/index.html ("Edit on github" at the top right", the flyout menu has a "Github: view/edit" link)

Not sure why. I'm guessing it's because Bazel is handling everything instead of readthedocs. Usually with readthedocs, the config file specifies:
  * python version to use
  * requirements file to install
  * Sphinx config file being used
  * Specific formats to build

And this gets translated into various `pip install` and `sphinx-build` commands.

e.g. here's some of the build log from rules_testing, which uses the readthedocs.yml config file:

```
python -mvirtualenv $READTHEDOCS_VIRTUALENV_PATH
python -m pip install --upgrade --no-cache-dir pip setuptools
python -m pip install --upgrade --no-cache-dir sphinx readthedocs-sphinx-ext
python -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
npm install -g @bazel/bazelisk
bazel run //docs:run_sphinx_build
cat docs/source/conf.py
python -m sphinx -T -E -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html
python -m sphinx -T -E -b readthedocssinglehtmllocalmedia -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/htmlzip
python -m sphinx -T -E -b latex -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/pdf
cat latexmkrc
latexmk -r latexmkrc -pdf -f -dvi- -ps- -jobname=rules-testing -interaction=nonstopmode
```

Maybe it also has to do with the environment variables? I noticed that environment variables aren't passed through to the `actions.run` call for running Sphinx. Which is WAI as far as bazel is concerned, but maybe there is logic within one of the sphinx extensions that checks for those to activate special behavior.

### PR DESCRIPTION
**Pull request by rickeylev**
This fixes a few issues with the RTD doc building:

* Warning banner is now shown for PR requests
* Pages now link to the github source
* The footer now shows the git commit they were built at

This works by passing the RTD environment variables to the sphinx build process, which allows the conf.py file to get their values. Env vars are passed by a new flag, `--//sphinxdocs:extra_env`, which allows passing arbitrary environment variable values into the sphinx build process. To make future usage of the RTD env vars easier, the build process passes along all the `READTHEDOCS*` environment variables.

Fixes #1516

### CODE REVIEW

**Review by aignas — APPROVED** [review]

File: docs/sphinx/readthedocs_build.sh [hunk 1]
```diff
@@ -0,0 +1,18 @@
+#!/bin/bash
+
```
Comment (aignas) [inline docs/sphinx/readthedocs_build.sh:2]: Nit: using `set -euo pipefail` would be good here, but the impl looks good.

Comment (rickeylev) [reply docs/sphinx/readthedocs_build.sh:2]: Done
